#!/usr/bin/env bash

set -e
set -x


# This script is invoked during CI build with the following arguments:
target_image_name=$1
# app_name=$2
# app_version=$3

docker build -t ${target_image_name} .
